version: '3'
networks:
    testnetwork:
        external: true
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 50:80
        restart: always
        depends_on:
            - php
            - database
        networks:
            - testnetwork
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
        networks:
            - testnetwork
    composer:
        image: composer:1.9
        command: ["composer", "install"]
        volumes:
            - .:/app
        networks:
            - testnetwork
    database:
        image: postgres:10
        environment:
            - "POSTGRES_DB=test"
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
        ports:
            - "5932:5432"
        #command: postgres -c config_file=/etc/postgresql.conf
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
        networks:
            - testnetwork
